// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsxolofuefhjbphautqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzeG9sb2Z1ZWZoamJwaGF1dHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNTY3NzAsImV4cCI6MjA3MzczMjc3MH0.KL2rNPu2bfLOwo1qjT6fAjB0C3KbbOM3BeeLD-Jg6sY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});