// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjpniltbpjfcwtcjicxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcG5pbHRicGpmY3d0Y2ppY3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NjMyMTksImV4cCI6MjA4NzAzOTIxOX0.KymILShDbYXyyFvK-ObBMy_GcD5zTaDV0Zb_Epe4ZBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});